#
#  Makefile for the kernel Sensor device drivers.
#

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_HSCD) 		+=hscd_i2c.o alps-input.o bma222.o bma222e.o
obj-$(CONFIG_PROXIMITY_SENSOR)	+= gp2a.o

